"""add platform_status, instance_network_status table

Revision ID: 1cbeb2b93488
Revises: 2f3ecb102a78
Create Date: 2015-05-20 14:58:55.265600

"""

# revision identifiers, used by Alembic.
revision = '1cbeb2b93488'
down_revision = '2f3ecb102a78'
branch_labels = None
depends_on = None

import sentry
from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sentry.db.sqlalchemy.models.LocalDateTime(),
              nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ps_hostname_idx', 'platform_status', ['hostname'],
                    unique=False)
    op.create_index('ps_hostname_item_idx', 'platform_status',
                    ['hostname', 'item_name', 'item_type'], unique=False)
    op.create_index('ps_state_idx', 'platform_status', ['state'], unique=False)
    op.create_table('instance_network_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=50), nullable=True),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sentry.db.sqlalchemy.models.LocalDateTime(),
              nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ins_hostname_idx', 'instance_network_status',
                    ['hostname'], unique=False)
    op.create_index('ins_hostname_uuid_idx', 'instance_network_status',
                    ['hostname', 'uuid'], unique=False)
    op.create_index('ins_state_idx', 'instance_network_status', ['state'],
                    unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ins_state_idx', table_name='instance_network_status')
    op.drop_index('ins_hostname_uuid_idx',
                  table_name='instance_network_status')
    op.drop_index('ins_hostname_idx', table_name='instance_network_status')
    op.drop_table('instance_network_status')
    op.drop_index('ps_state_idx', table_name='platform_status')
    op.drop_index('ps_hostname_item_idx', table_name='platform_status')
    op.drop_index('ps_hostname_idx', table_name='platform_status')
    op.drop_table('platform_status')
    ### end Alembic commands ###
