"""Create event, raw tables

Revision ID: 29114b357bef
Revises:
Create Date: 2015-01-01 12:01:32.788399

"""

# revision identifiers, used by Alembic.
revision = '29114b357bef'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('raw_message', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('roles', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('publisher_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('hostname', sa.String(length=50), nullable=True),
    sa.Column('binary', sa.String(length=20), nullable=True),
    sa.Column('service', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['raw_message'], ['raw_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('event_message_id', 'events',
                    ['message_id'], unique=False)
    op.create_index('project_id_x_user_id_idx', 'events',
                    ['project_id', 'user_id'], unique=False)
    op.create_index('project_name_x_user_name_idx', 'events',
                    ['project_name', 'user_name'], unique=False)
    op.create_index('request_id', 'events',
                    ['request_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('request_id', table_name='events')
    op.drop_index('project_name_x_user_name_idx', table_name='events')
    op.drop_index('project_id_x_user_id_idx', table_name='events')
    op.drop_index('event_message_id', table_name='events')
    op.drop_table('events')
    op.drop_table('raw_messages')
    ### end Alembic commands ###
