"""Add index timestamp for events

Revision ID: 2f140d7d1410
Revises: a2956c1b213
Create Date: 2015-02-27 14:40:19.861404

"""

# revision identifiers, used by Alembic.
revision = '2f140d7d1410'
down_revision = 'a2956c1b213'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('event_timestamp_idx', 'events',
                    ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('event_timestamp_idx', table_name='events')
    ### end Alembic commands ###
