"""Create all field indexes

Revision ID: 2f83c6521511
Revises: 56b71b6b980a
Create Date: 2015-01-23 16:55:37.036106

"""

# revision identifiers, used by Alembic.
revision = '2f83c6521511'
down_revision = '56b71b6b980a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('timestamp_x_event_message_id', 'events',
                    ['timestamp', 'message_id'], unique=False)
    op.create_index('timestamp_x_project_id_x_user_id_idx', 'events',
                    ['timestamp', 'project_id', 'user_id'], unique=False)
    op.create_index('timestamp_x_project_name_x_user_name_idx', 'events',
                    ['timestamp', 'project_name', 'user_name'], unique=False)
    op.create_index('timestamp_x_request_id', 'events',
                    ['timestamp', 'request_id'], unique=False)
    op.create_index(
        'timestamp_x_token_x_objectid_x_requestid_x_eventtype_x_b_x_s',
        'events',
        ['timestamp', 'token', 'object_id', 'request_id',
         'event_type', 'binary', 'service'], unique=False)
    op.drop_index(u'event_message_id', table_name='events')
    op.drop_index(u'project_id_x_user_id_idx', table_name='events')
    op.drop_index(u'project_name_x_user_name_idx', table_name='events')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'project_name_x_user_name_idx', 'events',
                    [u'project_name', u'user_name'], unique=False)
    op.create_index(u'project_id_x_user_id_idx', 'events',
                    [u'project_id', u'user_id'], unique=False)
    op.create_index(u'event_message_id', 'events',
                    [u'message_id'], unique=False)
    op.drop_index(
        'timestamp_x_token_x_objectid_x_requestid_x_eventtype_x_b_x_s',
        table_name='events')
    op.drop_index('timestamp_x_request_id', table_name='events')
    op.drop_index('timestamp_x_project_name_x_user_name_idx',
                  table_name='events')
    op.drop_index('timestamp_x_project_id_x_user_id_idx', table_name='events')
    op.drop_index('timestamp_x_event_message_id', table_name='events')
    ### end Alembic commands ###
