"""Fix events indexes

Revision ID: a2956c1b213
Revises: 2f83c6521511
Create Date: 2015-02-27 10:14:05.624426

"""

# revision identifiers, used by Alembic.
revision = 'a2956c1b213'
down_revision = '2f83c6521511'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('event_obj_id_req_id', 'events',
                    ['object_id', 'request_id', 'timestamp'], unique=False)
    op.create_index('event_req_id', 'events',
                    ['request_id', 'timestamp'], unique=False)
    op.create_index('event_uname_obj_id_req_id_idx', 'events',
                    ['user_name', 'object_id', 'request_id', 'timestamp'],
                    unique=False)
    op.drop_index(u'timestamp_x_event_message_id', table_name='events')
    op.drop_index(u'timestamp_x_project_id_x_user_id_idx', table_name='events')
    op.drop_index(u'timestamp_x_project_name_x_user_name_idx',
                  table_name='events')
    op.drop_index(u'timestamp_x_request_id', table_name='events')
    op.drop_index(
        u'timestamp_x_token_x_objectid_x_requestid_x_eventtype_x_b_x_s',
        table_name='events')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        u'timestamp_x_token_x_objectid_x_requestid_x_eventtype_x_b_x_s',
        'events',
        [u'timestamp', u'token', u'object_id', u'request_id',
         u'event_type', u'binary', u'service'], unique=False)
    op.create_index(u'timestamp_x_request_id', 'events',
                    [u'timestamp', u'request_id'], unique=False)
    op.create_index(u'timestamp_x_project_name_x_user_name_idx', 'events',
                    [u'timestamp', u'project_name', u'user_name'],
                    unique=False)
    op.create_index(u'timestamp_x_project_id_x_user_id_idx', 'events',
                    [u'timestamp', u'project_id', u'user_id'], unique=False)
    op.create_index(u'timestamp_x_event_message_id', 'events',
                    [u'timestamp', u'message_id'], unique=False)
    op.drop_index('event_uname_obj_id_req_id_idx', table_name='events')
    op.drop_index('event_req_id', table_name='events')
    op.drop_index('event_obj_id_req_id', table_name='events')
    ### end Alembic commands ###
